### ISSUE TITLE
Config/environment import in app.js

### ISSUE THREAD

**Issue by fedegos** [ember-learn/super-rentals#55]
I have the following question: the import directive of the environment.js module on app.js file is './config/environment' instead of '../config/environment/'. Although it works as expected, I cannot understand how does it work, and why the more obvious '../config/environment/' doesn't work.

**Comment by ef4** [comment]
This is a good question. The reason has to do with ember-cli's conventions for combining files and packaging them for the browser.

ember-cli takes everything under the `app` directory and builds it as AMD modules namespaced under your application's name. So `app/app.js` becomes the AMD module `super-rentals/app` and `app/components/list-filter.js` becomes `super-rentals/components/list-filter`. You can access them in the browser console like `require('super-rentals/app')`.

The config directory gets handled differently because it needs to be evaluated in node. For example, that is where the name "super-rentals" comes from in the first place.  But it's also useful to have access to config/environment from within the browser, so it *also* gets converted into an AMD module named `super-rentals/config/environment`.

Therefore, once you app is running in the browser, it's a case of `super-rentals/app` requiring `super-rentals/config/environment`, so './config/environment' works but '../config/environment' does not.
